### PR TITLE
fix/TLG-9: disallow input to accept negative integers

### LINKED ISSUE #9: disallow input to accept negative integers
If you set seconds in negative the app goes haywire.
This should be a constraint that the input should only accept positive integers.

### PR DESCRIPTION
**Pull request by Kaav-notabot**
Closes #9 
Addition to the fix, I have also removed redundant dependencies.

### CODE REVIEW

File: game/the-language-game.jsx [hunk 1]
```diff
@@ -178,7 +178,7 @@ const TheLanguageGame = ( props ) => {
 			{ ! gameStatus && <div tabIndex={ 0 } role="button" className="tlg-app__scoreboard-button" onClick={ () => setScoreboardStatus( ! scoreboardStatus ) } onKeyDown={ () => setScoreboardStatus( true ) }>Scoreboard</div> }
 			<div className="tlg-app__container">
 				<div className={ `tlg-app__syllable ${ markStatus ? 'has-text-primary' : '' }` }>{ currentSyllable }</div>
-				{ ! gameStatus && <input placeholder="Speed (in seconds)" className="input is-primary" id="tlg-speed-input" type="number" onChange={ ( e ) => updateSpeed( e.target.value ) } /> }
+				{ ! gameStatus && <input placeholder="Speed (in seconds)" className="input is-primary" id="tlg-speed-input" type="number" value={ speed } onChange={ ( e ) => updateSpeed( Number( e.target.value ) < 1 && '' !== e.target.value ? 1 : e.target.value ) } /> }
```
Comment (Sidsector9) [inline game/the-language-game.jsx:181]: 👍

**Comment by Sidsector9** [comment]
First contribution! 🎊
